POST {{url}}/admin/login?captcha=1234
Content-Type: application/json

{
"credentials": {
"email": "{{email}}",
"password": "{{password}}"
},
"vaccineSerialNumber": "test",
"vaccineExpiration": "2024-06-04T00:00:00.000Z"
}
> {% client.global.set("auth_token", response.body["token"]); %}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 0
}
###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 2999
}
###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 5998
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 8997
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 11996
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 14995
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 17994
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 20993
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 22992
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 24991
}

###
POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "exportPatientsInfo": true,
  "checkVaccinations": true,
  "exportVaccinationsFirstDose": true,
  "exportVaccinationsSecondDose": true,
  "validatePatients": true,
  "patientsCount": 3000,
  "patientsOffset": 26990
}

