POST {{url}}/admin/login?captcha=1234
Content-Type: application/json

{
  "credentials": {
    "email": "{{email}}",
    "password": "{{password}}"
  },
  "vaccineSerialNumber": "test",
  "vaccineExpiration": "2024-06-04T00:00:00.000Z"
}
> {% client.global.set("auth_token", response.body["token"]); %}

###
# Add admin in case you are running the request on previous staging/production
GET {{url}}/statistics
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

POST {{url}}/admin/locations?captcha=1234
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "address": "Strossmayerovo náměstí 4",
  "district": "Praha 7",
  "email": "ockovani@praha7.cz",
  "notes": "ZŠ Strossmayerovo náměstí",
  "phoneNumber": {
    "countryCode": "CZ",
    "number": "734521840"
  },
  "zipCode": 17000
}
> {% client.global.set("location_id", response.body["id"]); %}

###

POST {{url}}/admin/vaccination-slots?captcha=1234
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "locationId": "{{location_id}}",
  "from": "2021-06-11T05:00:00.00000000Z",
  "to": "2021-06-11T10:45:00.00000000Z",
  "bandwidth": 1,
  "durationMillis": 300000,
  "queueOffset": 0
}

###

POST {{url}}/patient?captcha=1234
Content-Type: application/json

{
  "firstName": "Adéla",
  "lastName": "Kostičková",
  "personalNumber": "9151010385",
  "email": "kubant.jan@example.com",
  "phoneNumber": {
    "countryCode": "CZ",
    "number": "602123534"
  },
  "zipCode": 10000,
  "district": "p",
  "answers": [
    {
      "questionId": "9a5587a1-dc43-49f3-9847-b736127c9e39",
      "value": false
    },
    {
      "questionId": "f4ca8d25-faaa-4b2f-abc2-3d7a8702d4a3",
      "value": false
    },
    {
      "questionId": "f5cf0689-a4d7-4c42-8107-6eaedca88a93",
      "value": false
    },
    {
      "questionId": "f68d221d-27a1-4c81-bf45-07b1f0290e15",
      "value": false
    },
    {
      "questionId": "f74ebe1e-ef94-4af0-963d-97ffab086b6b",
      "value": false
    },
    {
      "questionId": "f9c99047-0f44-4dfe-9964-71274a7af5e9",
      "value": false
    },
    {
      "questionId": "112f5fbd-cde2-4fe9-8cab-f5b4fff57296",
      "value": false
    },
    {
      "questionId": "7b02b12a-abb4-45d3-8bf4-0b074e445f37",
      "value": false
    }
  ],
  "insuranceCompany": "VZP",
  "confirmation": {
    "covid19VaccinationAgreement": true,
    "healthStateDisclosureConfirmation": true,
    "gdprAgreement": true
  }
}
###

// find patient
GET {{url}}/admin/patient?personalOrInsuranceNumber=1234567989
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.global.set("patient_id", response.body["id"]); %}

###

POST {{url}}/admin/data-correctness
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "dataAreCorrect":true,
  "notes":"note",
  "patientId":"{{patient_id}}"
}

###

// register user
POST {{url}}/admin/register?captcha=1234
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "firstName": "Petra",
  "lastName": "Nováková",
  "email": "petra@seznam.cz",
  "password": "pass",
  "role": "RECEPTIONIST"
}

###

POST {{url}}/admin/run-isin-job
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "validatePatients": true,
  "checkVaccinations": true,
  "exportPatientsInfo": false,
  "exportVaccinations": false,

  "patientsCount": null,
  "patientsOffset": 0
}
